# Generated by Django 5.1.6 on 2025-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin título', max_length=200)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card de Automóvil',
                'verbose_name_plural': 'Cards de Automóviles',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
